# dpmm_esa_continual_config.yaml
# Basato su dpmm_esa_global_config con aggiunta di Replay Buffer per apprendimento continuo

base_dir: "./datasets"           
exp_dir: "experiments_continual"
dataset: "esa"               
mission_id: 1
model: "dpmm"
dpmm_type: "diagonal"            
dpmm_mode: "likelihood_threshold"
detector: "threshold"
segmentator: false
challenge: false

# Parametri per Continual Learning
replay: "time-decay"
buffer_size: 100000
sample_size: 20000
half_life: 10000
experience_size: "360D"
train_start_date: "2000-01-01"
train_end_date: "2002-12-31"
test_start_date: "2003-01-01"


detector_params:
  quantile: 1.0
  smoothing_alpha: 0.7
  threshold_alpha: 0.5

replay_detector_params:
  quantile: 0.8
  smoothing_alpha: 0.7
  threshold_alpha: 0.5

eval_perc: 0.6
filter_valid: true

feature_extractor: 
  - "base_statistics"

feature_extraction_params:
  max_features: 5
  selected_features: null
  
window_size: null
step_size: null
max_window: 500
min_window: 150
perc_step_size: 0.5

channels: null

base_classifier_params:
  dynamic_scaling: true
  scaler_window: 1000
  n_clusters: 100
  num_iterations: 200
  lr: 0.5
  alpha_dp: 3.0
  var_prior: 3.0
  var_prior_strength: 1.0
  mu_prior_strength: 0.001
  quantile: 0.001
  return_likelihood: true
