
base_dir: "./datasets"           
exp_dir: "experiments"
dataset: "esa"               
mission_id: 1
model: "dpmm"
dpmm_type: "unit"            
dpmm_mode: "likelihood_threshold"
detector: 
  - "molookde"
segmentator: false
perc_eval: 0.3
challenge: false
feature_extractor: 
  - "base_statistics"

feature_extraction_params:
  max_features: 5
  selected_features: null
  
window_size: null
step_size: null
max_window: 500
min_window: 150
perc_step_size: 0.5

base_classifier_params: 
  dynamic_scaling: 
    - true
    - false
  scaler_window: 1000
  n_clusters: 100
  num_iterations: 1000
  patience: 100
  min_delta: 0.001
  restore_best: true
  lr: 0.1
  alpha_dp: 
    - 1.0
    - 3.0
    - 5.0
  var_prior: 3.0
  var_prior_strength: 0.001
  mu_prior_strength: 0.001
  quantile: 0.0001
  return_likelihood: false

channels: null
  

detector_params:
  alpha: [0.05, 0.01]
  p: [3.0, 5.0, 10.0]
  unitize: true
  pot_percentile: 95.0
  smoothing_alpha: 0.2
  min_allowed_ll: -200.0
