# dpmm_esa_global_config.yaml

base_dir: "./datasets"           
exp_dir: "experiments"
dataset: "esa"               
mission_id: 1
model: "dpmm"
dpmm_type: ["full", "diagonal", "unit", "single"]            
dpmm_mode: "likelihood_threshold"
detector: "threshold"
segmentator: true
challenge: false
save_metadata: false

detector_params:
  quantile: [2.0, 2.5]
  smoothing_alpha: [0.1, 0.3, 0.4, 1.0]

calibration_perc: 0.30

temporal_validation: true
val_train_end_date: "2005-01-01"
val_test_start_date: "2005-01-01"
val_test_end_date: "2007-01-01"

filter_valid: true
# Modular Feature Extraction
feature_extractor: 
  - "base_statistics"

feature_extraction_params:
  max_features: 5
  selected_features: null
  
window_size: null
step_size: null
max_window: 500
min_window: 150
perc_step_size: 0.5

channels: null

base_classifier_params:
  dynamic_scaling: [true, false]
  scaler_window: 1000
  n_clusters: 100
  num_iterations: 200
  lr: 0.5
  alpha_dp: 3.0
  var_prior: 3.0
  var_prior_strength: 1.0
  mu_prior_strength: 0.001
  quantile: 0.001
  return_likelihood: true
 
#detector_params:
  #alpha: 0.002
  #p: 3.0
  #unitize: true
  #pot_percentile: 93.0
  #smoothing_alpha: 0.2
  #min_allowed_ll: -200.0
