# dpmm_nasa_config.yaml
# Configurazione per esperimenti non-continual (run_segment_extraction_exp.py) su dataset NASA

base_dir: "./datasets"           
exp_dir: "experiments"
dataset: "nasa"               
mission_id: 1
model: "dpmm"
dpmm_type: "unit"            
dpmm_mode: "likelihood_threshold"
#detector: "molookde"
segmentator: false
feature_extractor: "base_statistics"
feature_extraction_params:
  selected_features:
    - "var"
    - "peak_to_peak_amplitude"
    - "internal_matrix_profile_max"
    - "spectral_centroid"
    - "smooth10_n_peaks"
    - "dom_freq_energy"
    - "spectral_entropy"

window_size: null
step_size: null
min_window: 20
max_window: 100
perc_step_size: 0.5
eval_perc: null

channels: null

base_classifier_params:
  dynamic_scaling: true
  scaler_window: 20
  n_clusters: 100
  num_iterations: 100
  lr: 0.1
  alpha_dp: 0.1
  var_prior: 5.0
  var_prior_strength: 1.0
  mu_prior_strength: 0.001
  quantile: 0.00001
  


