# dpmm_unit_config.yaml
base_dir: "./datasets"           
exp_dir: "experiments"
dataset: "esa"               
mission_id: 1
model: "dpmm"
dpmm_type: "unit"            
dpmm_mode: "likelihood_threshold"
detector: "molookde"
segmentator: false
feature_extractor: "base_statistics"
drift_detector: false
window_size: 100
step_size: 100
experience_size: "30D"

channels:
  - "channel_41"
  - "channel_42"
  - "channel_43"
  - "channel_44"
  - "channel_45"
  - "channel_46"

wrapper_params:
  eval_perc: 0.6
  alpha_buffer: 0.05


replay_params:
  max_size: 100000
  half_life_segments: "180D"
  min_prob: 0.000001 # 1e-6 in formato yaml esplicito per sicurezza del parser


detector_params:
  alpha: 0.05
  p: 3.0
  pot_percentile: 99.0


base_classifier_params:
  n_clusters: 100
  num_iterations: 1000
  lr: 0.1
  alpha_dp: 1.0
  var_prior: 1.0
  var_prior_strength: 1.0
  mu_prior_strength: 0.001
  quantile: 0.05


feature_extraction_params:
  selected_features:
    - "var"
    - "std"
    - "diff2_var"
    - "skew"
    - "dom_freq_energy"
    - "dom_freq_index"
    - "spectral_centroid"