# dpmm_esa_global_config.yaml
# Esperimenti su ESA con Modular Global Features

base_dir: "./datasets"           
exp_dir: "experiments"
dataset: "esa"               
mission_id: 1
model: "dpmm"
dpmm_type: "unit"            
dpmm_mode: "likelihood_threshold"
detector: "molookde"
segmentator: false

perc_eval: 0.3
# Modular Feature Extraction
feature_extractor: 
  - "base_statistics"

feature_extraction_params:
  max_features: 5
  selected_features: null
  
window_size: null
step_size: null
max_window: 500
min_window: 150
perc_step_size: 0.5

channels: null


base_classifier_params:
  dynamic_scaling: true
  scaler_window: 1000
  n_clusters: 100
  num_iterations: 100
  lr: 0.5
  alpha_dp: 3.0
  var_prior: 3.0
  var_prior_strength: 1.0
  mu_prior_strength: 0.001
  quantile: 0.001
  return_likelihood: true

detector_params:
  alpha: 0.002
  p: 3.0
  unitize: true
  pot_percentile: 93.0
  smoothing_alpha: 0.2
  min_allowed_ll: -200.0
