# iforest_esa_deep.yaml
# Profilo: Deep Isolation (Precisione)
base_dir: "./datasets"           
exp_dir: "experiments_iforest_deep"
dataset: "esa"               
mission_id: 1
model: "iforest"
detector: "threshold"

window_size: 100
step_size: 50
perc_step_size: 0.5

feature_extractor: "base_statistics"
feature_extraction_params:
  max_features: 10

channels: ["channel_41", "channel_42", "channel_43", "channel_44", "channel_45", "channel_46"]

base_classifier_params:
  n_estimators: 500
  contamination: 0.01
  max_samples: 512
  random_state: 42
  
detector_params:
  threshold: 0.999
