# telemanom_esa_config.yaml
# Test configuration for Telemanom integration

base_dir: "./datasets"           
exp_dir: "experiments_telemanom"
dataset: "esa"               
mission_id: 1
model: "telemanom"
feature_extractor: "none"
use_telecommands: False
segmentator: false
n_predictions: 10

base_classifier_params:
  criterion: MSELoss
  optimizer: Adam
  n_predictions: 10
  reduce_out: mean
  epochs: 1000
  p: 0
  patience: 20

channels:
  - "channel_41"
  - "channel_42"
  - "channel_43"
  - "channel_44"
  - "channel_45"
  - "channel_46"