# test_sml_e2e.yaml
base_dir: "./datasets"           
exp_dir: "experiments_sml"
dataset: "esa"               
mission_id: 1
model: "dpmm"
dpmm_type: "unit"            
dpmm_mode: "likelihood_threshold"
detector: "threshold"
segmentator: false
perc_eval: 0.3

# Modular Feature Extraction
feature_extractor: 
  - "base_statistics"

feature_extraction_params:
  max_features: 5
  
window_size: null
step_size: null
max_window: 500
min_window: 150
perc_step_size: 0.5

base_classifier_params:
  dynamic_scaling: true
  scaler_window: 1000
  n_clusters: 100
  num_iterations: 1000
  lr: 0.5
  alpha_dp: 3.0
  var_prior: 3.0

detector_params:
  alpha: 0.01
  pot_percentile: 90.0
