base_dir: "./datasets"           
exp_dir: "experiments"
dataset: "nasa"               
mission_id: 1                  
model: "dpmm"
dpmm_type: "unit"            
dpmm_mode: "likelihood_threshold"

challenge: false
detector: "dpmm_native"  
feature_extractor: "base_statistics"

perc_eval: 0.3
window_size: null         
step_size: null
perc_step_size: 1.0

base_classifier_params:
  dynamic_scaling: true
  scaler_window: 100
  n_clusters: 10
  num_iterations: 1000
  patience: 100
  min_delta: 0.001
  restore_best: true
  lr: 0.1
  alpha_dp: 3.0
  var_prior: 3.0
  var_prior_strength: 0.001
  mu_prior_strength: 0.001
  quantile: 0.0001

feature_extraction_params:
  max_features: null
  selected_features: 
    - "spectral_centroid"
    - "smooth10_n_peaks"
    - "fractal_roughness"
    - "kurtosis"

channels: null
