# test_nasa_sml.yaml
base_dir: "./datasets"           
exp_dir: "experiments_nasa_sml"
dataset: "nasa"               
model: "dpmm"
dpmm_type: "unit"            
dpmm_mode: "likelihood_threshold"
detector: "threshold"
segmentator: false
perc_eval: 0.3

# Modular Feature Extraction
feature_extractor: 
  - "base_statistics"

feature_extraction_params:
  max_features: 5
  
window_size: 100
step_size: 50

base_classifier_params:
  dynamic_scaling: true
  scaler_window: 500
  n_clusters: 50
  num_iterations: 100
  lr: 0.5
  alpha_dp: 3.0
  var_prior: 3.0

detector_params:
  alpha: 0.05
  pot_percentile: 90.0
